import net.pricefx.common.api.chart.FilterOperator

if (out.ProductId != null) {
    return api.newChartBuilder()
            .newWaterfall()
            .getOptions()
            .setHideTooltips(false)
            .back()
            .getSeries()
            .setLabel('Review Waterfall Deployed')
            .setDatamart('DM.PricelistItems')
            .setCurrency('EUR')
            .getAggregation().withTotal().back()
            .setHideDataLabels(false)
            .addWaterfallColumn(WaterfallColumnType.RESULT, 'ResultPrice', 'ResultPrice')
            .addProductsFilter()
            .addFilters(FilterOperator.AND)
            .addFilter('ProductId', FilterOperator.EQUAL, out.ProductId)
            .back()
            .back()
            .back()
            .getDictionary()
            .buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"","key":"y","keyLabel":"Axis Y","sectionLabel":"Review Waterfall","seriesIndex":0}]')
            .back()
            .build()
} else {
    return api.newChartBuilder()
            .newWaterfall()
            .getOptions()
            .setHideTooltips(false)
            .back()
            .getSeries()
            .setLabel('Review Waterfall Deployed')
            .setDatamart('DM.PricelistItems')
            .setCurrency('EUR')
            .getAggregation().withTotal().back()
            .setHideDataLabels(false)
            .addWaterfallColumn(WaterfallColumnType.RESULT, 'ResultPrice', 'ResultPrice')
            .addProductsFilter()
            .addFilters(FilterOperator.AND)
            .addFilter('ProductId', FilterOperator.IN_SET, ["MB-0001","MB-0002","MB-0003","MB-0004","MB-0005","MB-0006","MB-0007","MB-0008","MB-0009","MB-0010","MB-0060","MB-0059","MB-0053","MB-0052","MB-0051","MB-0050"])
            .back()
            .back()
            .back()
            .getDictionary()
            .buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"","key":"y","keyLabel":"Axis Y","sectionLabel":"Review Waterfall","seriesIndex":0}]')
            .back()
            .build()
}