def chart = api.newChartBuilder()
        .newScatter()
        .getOptions()
        .setHideLegend(false)
        .setHideTooltips(false)
        .setDisableDrilldown(false)
        .setDisableZoom(false)
        .setDiscretization(true)
        .setDisableGridDiscretization(false)
        .back()
        .addSeries()
        .setLabel('Review Scatter Deployed')
        .setDatamart('DM.PricelistItems')
        .setCurrency('USD')
        .setAxisX('ProductId').withAggregation('COUNT').back()
        .setAxisY('ResultPrice').withTotal().back()
        .setAggregationBy('ProductId')
        .setBandBy('ProductId')
        .back()
        .getDictionary()
        .buildFromOpaqueString('[{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"#(ProductId)","field":{"name":"ProductId","rank":1,"visibility":1,"expression":"ProductId","system":false,"key":true,"partitioningKey":false,"distributionKey":false,"persisted":true,"calculated":false,"aggregation":false,"deployed":true,"dimension":true,"dbColumn":"attribute1","queryable":true,"dbTable":"dm_pricelistitems","auxiliary":false,"numeric":false,"type":"TEXT","time":false,"messages":{},"label":"ProductId"},"key":"x","keyLabel":"Axis X","sectionLabel":"ReviewScatter","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"∑ResultPrice","field":{"name":"ResultPrice","rank":3,"visibility":1,"expression":"ResultPrice","system":false,"key":false,"partitioningKey":false,"distributionKey":false,"persisted":true,"calculated":false,"aggregation":false,"deployed":true,"dimension":false,"dbColumn":"attribute3","queryable":true,"dbTable":"dm_pricelistitems","auxiliary":false,"numeric":true,"type":"MONEY","time":false,"messages":{},"label":"ResultPrice"},"key":"y","keyLabel":"Axis Y","sectionLabel":"ReviewScatter","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"ProductId","field":{"name":"ProductId","rank":1,"visibility":1,"expression":"ProductId","system":false,"key":true,"partitioningKey":false,"distributionKey":false,"persisted":true,"calculated":false,"aggregation":false,"deployed":true,"dimension":true,"dbColumn":"attribute1","queryable":true,"dbTable":"dm_pricelistitems","auxiliary":false,"numeric":false,"type":"TEXT","time":false,"messages":{},"label":"ProductId"},"key":"groupBy","keyLabel":"Aggregation By","sectionLabel":"ReviewScatter","seriesIndex":0},{"sectionIdx":1,"category":"PROJECTION","categoryLabel":"Projection","defaultValue":"ProductId","field":{"name":"ProductId","rank":1,"visibility":1,"expression":"ProductId","system":false,"key":true,"partitioningKey":false,"distributionKey":false,"persisted":true,"calculated":false,"aggregation":false,"deployed":true,"dimension":true,"dbColumn":"attribute1","queryable":true,"dbTable":"dm_pricelistitems","auxiliary":false,"numeric":false,"type":"TEXT","time":false,"messages":{},"label":"ProductId"},"key":"bandBy","keyLabel":"Band By","sectionLabel":"ReviewScatter","seriesIndex":0}]')
        .back()
        .build()

return chart